name: Hello World
on: push
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello, Github action"
          echo "Create a file"
          echo "hello" > output.txt
          cat output.txt
