name: Nightly Build
on:
  schedule:
    - cron: '16 4 * * *'
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Run nightly tests
        run: |
          echo "Nightly build is started at $(date)"
          echo " Running full test suite"
